### PR TITLE
Disable shadow variable errors

### PR DESCRIPTION
**Pull request by peteshand**
Disable shadow variable errors with `bEnableShadowVariableWarnings = false;`

While redefined local variables aren't ideal, Haxe's output is done in a safe manner, so it's safe to ignore these errors

### CODE REVIEW

**Comment by SomeRanDev** [comment]
Oh nice! I've been avoiding this issue by adding `#pragma disable` to all the source files, but have been desperately looking for a better way. Do you have a link to the ModuleRules C# documentation?? I've been scouring the internet for a list of properties that can be used, but have had next to no luck. It would help so much with this project to know what can be done with the rules stuff. ;_;

EDIT: lemme just test this real quick with the removal of the pragmas. I recall getting two types of these errors so wanna make sure it fixes both.

**Comment by SomeRanDev** [comment]
I'm getting an error? 
```
CS0103	The name 'bEnableShadowVariableWarnings' does not exist in the current context

SampleProject\Source\HaxeCompatibility\HaxeCompatibility.Build.cs
```

**Comment by peteshand** [comment]
Hmmm interesting.. I'm using it in a 4.27 project.. maybe it was removed / changed in the move to 5.x
It's getting late here, but I'll test in ue5 tomorrow

**Comment by peteshand** [comment]
I didn't find much in the way of documentation either.. I was search for a while and came across `bEnableShadowVariableWarnings` being mentioned in these releaseNotes:
https://docs.unrealengine.com/4.26/en-US/WhatsNew/Builds/ReleaseNotes/2015/4_8/

and then from there found this page for a few other settings:
https://dawnarc.com/2019/07/ue4unrealbuildtool-apis-in-common/

**Comment by SomeRanDev** [comment]
OOOH I got it.
```
ShadowVariableWarningLevel = WarningLevel.Warning;
```

I found the documentation here, idk why it was so hard before. Should definitely search through these more, one of the reasons this project has been so much work is cause hxcpp does not abide by the same errors as Unreal. Hopefully can find a few more to suppress so don't need to use a custom version of hxcpp.
5.0 - https://docs.unrealengine.com/5.0/en-US/modules/
4.27 - https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/BuildTools/UnrealBuildTool/ModuleFiles/

I just committed that, but if you want could you modify this pull so it uses both UE5 and UE4 with C# conditional compilation (*I'm not sure how to do it to check UE's version, but if we can support both, that would be nice.*)

**Comment by peteshand** [comment]
Nice find.
Cool, I've updated the pull request to have a conditional for UE5 / UE4
```
#if UE_5_0_OR_LATER
ShadowVariableWarningLevel = WarningLevel.Warning;
#else
bEnableShadowVariableWarnings = false;
#endif
```

**Pull request merged**
